### ISSUE TITLE
can you share the example?

### ISSUE THREAD

**Issue by GuangtaoLyu** [baldoarbol/BodyShapeGPT#1]
hello,
thank you for your great work.
can you share the example used in your demo video?
thank you.

**Comment by dancasas** [comment]
Hi, I am not sure I get what you mean by "the example used". 

For the demo video, we used the prompts visible in the clip ("short, pearl-shaped person", etc.). Our model outputs SMPL shape parameters given these prompts, which can be converted to human shapes by feeding them to SMPL. To render the meshes and composite the video, we used Blender.

What are you asking for specifically?

**Comment by GuangtaoLyu** [comment]
I apologize for the confusion.

Perhaps, what I meant to ask is how to use Blender to render SMPL meshes with textures applied. I've noticed that in other people's papers, the rendered results of SMPL meshes are often in a light blue or gray hue. However, I'm curious about how to add textured colors to the rendering outcome, similar to the appearance in your demo video.

**Comment by baldoarbol** [comment]
You can add textures to any SMPL-X mesh in Blender using the Blender add-on. Its integrated GUI allows you to render the model with male, female, or test textures, or even add your own. You may find the following videos useful:
[SMPL-X Blender Add-On -- Tutorial](https://youtu.be/DY2k29Jef94?si=Y6idJYueUOn48rCc), by Michael Black's youtube channel
[SMPL-X Application Integrations. Using SMPL-X in Blender, Unity and Unreal](url), by Michael Black's youtube channel

**Comment by GuangtaoLyu** [comment]
> You can add textures to any SMPL-X mesh in Blender using the Blender add-on. Its integrated GUI allows you to render the model with male, female, or test textures, or even add your own. You may find the following videos useful: [SMPL-X Blender Add-On -- Tutorial](https://youtu.be/DY2k29Jef94?si=Y6idJYueUOn48rCc), by Michael Black's youtube channel [SMPL-X Application Integrations. Using SMPL-X in Blender, Unity and Unreal](url), by Michael Black's youtube channel

ok, I got it. thank you for your reply.
